export const FILTER_SAMPLES = [
  ['hello there, nice collection', 'chat', null],
  ['Niger is a country in West Africa', 'chat', null],
  ['Scunthorpe United', 'chat', null],
  ['the analysis of a cockpit', 'chat', null],
  ['I have 1 000 000 coins', 'chat', null],
  ['snapshot of my binder', 'chat', null],
  ['sussex and essex', 'chat', null],
  ['a classic assassin', 'name', null],
  ['Mississippi_coffee', 'name', null],
  ['connexion', 'name', null],
  ['prickly pear', 'name', null],
  ['chatter', 'chat', null],
  ['n1gg3r', 'chat', 'WORD'],
  ['nigggger', 'chat', 'WORD'],
  ['Pédé', 'chat', 'WORD'],
  ['send nudes', 'chat', 'WORD'],
  ['sexxx', 'chat', 'WORD'],
  ['fuuuuck', 'name', 'WORD'],
  ['xX_fuck_Xx', 'name', 'WORD'],
  ['F u c k', 'name', 'WORD'],
  ['shiiit happens', 'name', 'WORD'],
  ['fuck this', 'chat', null],
  ['Admin_Bob', 'name', 'RESERVED'],
  ['WiksterStaff', 'name', 'RESERVED'],
  ['go to www.site.com', 'chat', 'LINK'],
  ['join discord.gg/abc', 'chat', 'LINK'],
  ['my number 06 12 34 56 78', 'chat', 'CONTACT'],
  ['call +33 6 12 34 56 78', 'chat', 'CONTACT'],
  ['write to me@mail.fr', 'chat', 'LINK'],
  ['add me on snap', 'chat', 'CONTACT'],
  ['my discord is bob', 'chat', 'CONTACT'],
  ['Star Wars Wiki', 'pack', null],
  ['Putain de pack', 'pack', 'WORD'],
  ['Les Connards', 'guild', 'WORD'],
  ['Official Readers', 'guild', 'RESERVED']
];
